# Generated by Django 5.2.8 on 2026-04-19 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_trueques', '0004_alter_mensaje_options_alter_producto_propietario'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
