# Generated by Django 5.2.8 on 2026-05-21 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_trueques', '0007_perfil_bio_perfil_ciudad_perfil_fecha_registro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
