# Generated by Django 5.2.8 on 2026-05-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_trueques', '0008_alter_perfil_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
