# Generated by Django 5.2.8 on 2026-09-04 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_trueques', '0009_alter_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='advertencia_ia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='es_seguro',
            field=models.BooleanField(default=True),
        ),
    ]
