# Generated by Django 5.2.8 on 2026-09-04 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_trueques', '0010_mensaje_advertencia_ia_mensaje_es_seguro'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='audio',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='contenido',
            field=models.TextField(blank=True, null=True),
        ),
    ]
