# Generated by Django 5.2.8 on 2026-09-04 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_trueques', '0011_mensaje_audio_alter_mensaje_contenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('electronica', 'Electrónica'), ('ropa', 'Ropa'), ('hogar', 'Hogar'), ('deportes', 'Deportes'), ('vehiculos', 'Vehículos'), ('otros', 'Otros')], default='otros', max_length=20),
        ),
    ]
